Algoritmo "Exercicio23Faccat"
// Disciplina   : [Lógica de Programação com VISUALG]
// Professor   : Jailson Costa dos Santos
// Descrição   : Ler um valor e escrever se é positivo ou negativo
// (considere o valor zero como positivo).
// Autor(a)    : Guilherme da Silva Varjao
// Data atual  : 12/04/2026
Var
   // Seção de Declarações das variáveis
   valor:inteiro



Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite um valor: ")
   leia(valor)
   se valor <0 entao
      Escreval("O valor é negativo")
   senao
      se valor >=0 entao
         Escreval("O valor é positivo")
   fimse
   fimse


Fimalgoritmo