Algoritmo "Exercicio28Faccat"
// Disciplina   : [Lógica de Programação com VISUALG]
// Professor   : Jailson Costa dos Santos
// Descrição   : Ler dois valores (considere que não serão lidos valores
// iguais) e escrever o maior deles.
// Autor(a)    : Guilherme da Silva Varjão
// Data atual  : 17/04/2026
Var
   // Seção de Declarações das variáveis
   valor1, valor2: inteiro




Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite um valor: ")
   leia(valor1)
   Escreval("Digite outro valor: ")
   leia(valor2)
   se valor1 > valor2 entao
      Escreval("O valor1 é maior")
      senão
     Escreval("O valor 2 é maior")
     fimse





Fimalgoritmo