Algoritmo "Exercicios17Faccat"
// Disciplina   : [Lógica de Programação com VISUALG]
// Professor   : Jailson Costa dos Santos 
// Descrição   : Escreva um programa para ler o raio de um círculo
// , calcular e escrever a sua área.
// Autor(a)    : Guilherme da Silva Varjão
// Data atual  : 12/04/2026
Var
// Seção de Declarações das variáveis 
    raio:real
    areaCirculo:real
    

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Digite o valor do raio do circulo: ")
   leia(raio)
   areaCirculo<-  3.14 * raio * raio
   Escreval("A área do círculo é: ", areaCirculo)



Fimalgoritmo